version: "3.9"
services:
    node_app:
        container_name: node_app
        build: .
        image: jayfronczesko/crud_rest_api
        ports: -"3000:3000"
        environment:
            - PG_DB=node_rest_db
            - PG_USER=jayfronczesko
            - PG_PASSWORD=zacisze32
            - PG_HOST=node_db
        depends_on:
            - node_db
        restarts: always

    node_db:
        container_name: node_db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=node_rest_db
            - POSTGRES_USER=jayfronczesko
            - POSTGRES_PASSWORD=zacisze32
        volumes:
            - node_db_data:/var/lib/postgresql/data

    volumes:
        node_db_data: {}
